### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by abc123desygn** [theovercomer8/sd-playground#1]
There's an error in the Start Dreambooth cell as soon as you start training.
<img width="1180" alt="Screenshot 2023-02-15 at 9 46 12 AM" src="https://user-images.githubusercontent.com/121518935/219045067-c4ccdc37-7db1-4a98-8fa1-9ee7c4d24f41.png">

**Comment by theovercomer8** [comment]
Marking as closed, this was an issue with using the wrong url.
